*NPD 2012/13

cd 

use"\mcs_cm_npd_absence_2013_restricted.dta", clear

*ID variables 
misstable summarize MCSID //no missing 
tab CNUM, m 

*generating person specific ID 
egen CMID = concat (MCSID CNUM)  if CNUM >0

sort CMID
codebook CMID if CMID ! =""
count if CMID != "" 
count if CMID == ""  

*duplicate IDs
duplicates list CMID
duplicates report CMID


duplicates tag CMID, generate(dup)

tab dup, m
sort dup CMID

gen one_school =.
replace one_school =1 if dup ==0
tab one_school, m

summ SESSIONSPOSSIBLE_5HTERM_AB13


*dfe guidance says schools should be open for at least 378 sessions 


summ SESSIONSPOSSIBLE_6HTERM_AB13




*adding together duplicate rows 
*convert long to wide so each row is one individual with a unique CMID 
*also need to decide whether to use 5 or 6 half terms 
bysort CMID: gen cmid_dup = _n
reshape wide  MCSID CNUM MAINRECORD_AB13 URN_ANON_13 LEA_ANON_13 ONROLL_1_AB13 ONROLL_2_AB13 ONROLL_3_AB13 ACADEMICYEAR_AB13 GENDER_AB13 YSSA_AB13 ENROLSTATUS_AB13 NCYEARACTUAL_AB13 SESSIONSPOSSIBLE_AUT_AB13 AUTHABSENCE_AUT_AB13 AUTHABSENCEFLAG_AUT_AB13 UNAUTHABSENCE_AUT_AB13 UNAUTHABSENCEFLAG_AUT_AB13 OVERALLABSENCE_AUT_AB13 SESSIONSPOSSIBLE_SPR_AB13 AUTHABSENCE_SPR_AB13 AUTHABSENCEFLAG_SPR_AB13 UNAUTHABSENCE_SPR_AB13 UNAUTHABSENCEFLAG_SPR_AB13 OVERALLABSENCE_SPR_AB13 SESSIONSPOSSIBLE_SUM_AB13 AUTHABSENCE_SUM_AB13 AUTHABSENCEFLAG_SUM_AB13 UNAUTHABSENCE_SUM_AB13 UNAUTHABSENCEFLAG_SUM_AB13 OVERALLABSENCE_SUM_AB13 SESSIONSPOSSIBLE_SUM6TH_AB13 AUTHABSENCE_SUM6TH_AB13 AUTHABSENCEFLAG_SUM6TH_AB13 UNAUTHABSENCE_SUM6TH_AB13 UNAUTHABSENCEFLAG_SUM6TH_AB13 OVERALLABSENCE_SUM6TH_AB13 SESSIONSPOSSIBLE_ANN_AB13 AUTHABSENCE_ANN_AB13 AUTHABSENCEFLAG_ANN_AB13 UNAUTHABSENCE_ANN_AB13 UNAUTHABSENCEFLAG_ANN_AB13 OVERALLABSENCE_ANN_AB13 SESSIONSPOSSIBLE_5HTERM_AB13 AUTHABSENCE_5HTERM_AB13 UNAUTHABSENCE_5HTERM_AB13 OVERALLABSENCE_5HTERM_AB13 SESSIONSPOSSIBLE_6HTERM_AB13 AUTHABSENCE_6HTERM_AB13 UNAUTHABSENCE_6HTERM_AB13 OVERALLABSENCE_6HTERM_AB13 , i (CMID) j (cmid_dup)

duplicates report CMID 



* 5 HALF TERMS

*sessions possible
replace SESSIONSPOSSIBLE_5HTERM_AB131 = 0 if SESSIONSPOSSIBLE_5HTERM_AB131 ==.
replace SESSIONSPOSSIBLE_5HTERM_AB132 = 0 if SESSIONSPOSSIBLE_5HTERM_AB132 ==.
replace SESSIONSPOSSIBLE_5HTERM_AB133 = 0 if SESSIONSPOSSIBLE_5HTERM_AB133 ==.


gen SESSIONSPOSSIBLE_5HTERM_AB13 = SESSIONSPOSSIBLE_5HTERM_AB131 + SESSIONSPOSSIBLE_5HTERM_AB132 + SESSIONSPOSSIBLE_5HTERM_AB133 

summ SESSIONSPOSSIBLE_5HTERM_AB13, detail



*overall absence 
replace OVERALLABSENCE_5HTERM_AB131  = 0 if OVERALLABSENCE_5HTERM_AB131 ==.
replace OVERALLABSENCE_5HTERM_AB132  = 0 if OVERALLABSENCE_5HTERM_AB132 ==.
replace OVERALLABSENCE_5HTERM_AB133  = 0 if OVERALLABSENCE_5HTERM_AB133 ==.


gen OVERALLABSENCE_5HTERM_AB13 = OVERALLABSENCE_5HTERM_AB131 + OVERALLABSENCE_5HTERM_AB132 + OVERALLABSENCE_5HTERM_AB133 

summ OVERALLABSENCE_5HTERM_AB13, detail

gen absence_rate_13_5ht =  OVERALLABSENCE_5HTERM_AB13 / SESSIONSPOSSIBLE_5HTERM_AB13 *100
summ absence_rate_13_5ht, detail

gen absence_bin_13_5ht =.
replace absence_bin_13_5ht =1 if absence_rate_13_5ht >= 10 & absence_rate_13_5ht !=.
replace absence_bin_13_5ht =0 if absence_rate_13_5ht < 10
tab absence_bin_13_5ht, m

label variable absence_bin_13_5ht "binary absence 2013 10% 5HT"


*is the academic year the same for the duplicate entries for the same MCSID? 
count if NCYEARACTUAL_AB131 != NCYEARACTUAL_AB132 & NCYEARACTUAL_AB132 !="" & NCYEARACTUAL_AB131 !="" 
count if NCYEARACTUAL_AB131 != NCYEARACTUAL_AB133 & NCYEARACTUAL_AB133 !="" & NCYEARACTUAL_AB131 !="" 
count if NCYEARACTUAL_AB132 != NCYEARACTUAL_AB133 & NCYEARACTUAL_AB132 !="" & NCYEARACTUAL_AB133 !="" 

list CMID MCSID1 if NCYEARACTUAL_AB131 != NCYEARACTUAL_AB132 & NCYEARACTUAL_AB132 !="" & NCYEARACTUAL_AB131 !=""

count if NCYEARACTUAL_AB131 =="" &  NCYEARACTUAL_AB132 !="" 
count if NCYEARACTUAL_AB131 =="" &  NCYEARACTUAL_AB133 !="" 
count if NCYEARACTUAL_AB132 =="" &  NCYEARACTUAL_AB133 !="" 

encode NCYEARACTUAL_AB131, gen (NCYEARACTUAL_AB131_num)
encode NCYEARACTUAL_AB132, gen (NCYEARACTUAL_AB132_num)
encode NCYEARACTUAL_AB133, gen (NCYEARACTUAL_AB133_num)


codebook NCYEARACTUAL_AB131_num
tab NCYEARACTUAL_AB131
tab NCYEARACTUAL_AB131_num, m
tab NCYEARACTUAL_AB132_num, m
tab NCYEARACTUAL_AB133_num, m

*1 = year 6
*2 = year 7
*3 = year 8
*4 = X?


gen NCYEARACTUAL_AB13 =.
replace NCYEARACTUAL_AB13 = NCYEARACTUAL_AB131_num
replace NCYEARACTUAL_AB13 = NCYEARACTUAL_AB132_num if NCYEARACTUAL_AB13 ==.
replace NCYEARACTUAL_AB13 = NCYEARACTUAL_AB133_num if NCYEARACTUAL_AB13 ==.

label variable NCYEARACTUAL_AB13 "which academic year yp was in in 2013"

label define ncyear13 1 "6" 2 "7" 3 "8" 
label values NCYEARACTUAL_AB13 ncyear13

tab  NCYEARACTUAL_AB13, m 
replace NCYEARACTUAL_AB13 =. if NCYEARACTUAL_AB13 ==4
tab  NCYEARACTUAL_AB13, m 


sort NCYEARACTUAL_AB13
	  

 

keep CMID absence_rate_13_5ht absence_bin_13_5ht absence13_flag NCYEARACTUAL_AB13 unauthabsence_rate_13_5ht   authabsence_rate_13_5ht one_school

replace one_school =0 if one_school ==.

misstable summarize 
save "Working\all_waves_data_files\npd_2013_w.dta", replace



