*NPD 2013/14

cd 

use\stata\stata11\mcs_cm_npd_absence_2014_restricted.dta", clear

*ID variables 
misstable summarize MCSID 
tab CNUM, m 

*generating person specific ID 
egen CMID = concat (MCSID CNUM)  if CNUM >0

sort CMID
codebook CMID if CMID ! =""
count if CMID != "" 
count if CMID == "" 
*duplicate IDs
duplicates list CMID
duplicates report CMID




duplicates tag CMID, generate(dup)


tab dup, m
sort dup CMID

gen one_school =.
replace one_school =1 if dup ==0
tab one_school, m

summ SESSIONSPOSSIBLE_5HTERM_AB14



*dfe guidance says schools in england should be open for at least 378 sessions per year


summ SESSIONSPOSSIBLE_6HTERM_AB14




*adding together duplicate rows 
*convert long to wide so each row is one individual with a unique CMID 
*also need to decide whether to use 5 or 6 half terms 
bysort CMID: gen cmid_dup = _n
reshape wide  MCSID CNUM MAINRECORD_AB14 URN_ANON_14 LEA_ANON_14 ONROLL_1_AB14 ONROLL_2_AB14 ONROLL_3_AB14 ACADEMICYEAR_AB14 GENDER_AB14 PHASE_AB14 YSSA_AB14 ENROLSTATUS_AB14 NCYEARACTUAL_AB14 SESSIONSPOSSIBLE_AUT_AB14 AUTHABSENCE_AUT_AB14 AUTHABSENCEFLAG_AUT_AB14 UNAUTHABSENCE_AUT_AB14 UNAUTHABSENCEFLAG_AUT_AB14 OVERALLABSENCE_AUT_AB14 SESSIONSPOSSIBLE_SPR_AB14 AUTHABSENCE_SPR_AB14 AUTHABSENCEFLAG_SPR_AB14 UNAUTHABSENCE_SPR_AB14 UNAUTHABSENCEFLAG_SPR_AB14 OVERALLABSENCE_SPR_AB14 SESSIONSPOSSIBLE_SUM_AB14 AUTHABSENCE_SUM_AB14 AUTHABSENCEFLAG_SUM_AB14 UNAUTHABSENCE_SUM_AB14 UNAUTHABSENCEFLAG_SUM_AB14 OVERALLABSENCE_SUM_AB14 SESSIONSPOSSIBLE_SUM6TH_AB14 AUTHABSENCE_SUM6TH_AB14 AUTHABSENCEFLAG_SUM6TH_AB14 UNAUTHABSENCE_SUM6TH_AB14 UNAUTHABSENCEFLAG_SUM6TH_AB14 OVERALLABSENCE_SUM6TH_AB14 SESSIONSPOSSIBLE_ANN_AB14 AUTHABSENCE_ANN_AB14 AUTHABSENCEFLAG_ANN_AB14 UNAUTHABSENCE_ANN_AB14 UNAUTHABSENCEFLAG_ANN_AB14 OVERALLABSENCE_ANN_AB14 SESSIONSPOSSIBLE_5HTERM_AB14 AUTHABSENCE_5HTERM_AB14 UNAUTHABSENCE_5HTERM_AB14 OVERALLABSENCE_5HTERM_AB14 SESSIONSPOSSIBLE_6HTERM_AB14 AUTHABSENCE_6HTERM_AB14 UNAUTHABSENCE_6HTERM_AB14 OVERALLABSENCE_6HTERM_AB14 , i (CMID) j (cmid_dup)

duplicates report CMID 



* 5 HALF TERMS

*sessions possible
replace SESSIONSPOSSIBLE_5HTERM_AB141 = 0 if SESSIONSPOSSIBLE_5HTERM_AB141 ==.
replace SESSIONSPOSSIBLE_5HTERM_AB142 = 0 if SESSIONSPOSSIBLE_5HTERM_AB142 ==.
replace SESSIONSPOSSIBLE_5HTERM_AB143 = 0 if SESSIONSPOSSIBLE_5HTERM_AB143 ==.


gen SESSIONSPOSSIBLE_5HTERM_AB14 = SESSIONSPOSSIBLE_5HTERM_AB141 + SESSIONSPOSSIBLE_5HTERM_AB142 + SESSIONSPOSSIBLE_5HTERM_AB143 

summ SESSIONSPOSSIBLE_5HTERM_AB14, detail




*overall absence 
replace OVERALLABSENCE_5HTERM_AB141  = 0 if OVERALLABSENCE_5HTERM_AB141 ==.
replace OVERALLABSENCE_5HTERM_AB142  = 0 if OVERALLABSENCE_5HTERM_AB142 ==.
replace OVERALLABSENCE_5HTERM_AB143  = 0 if OVERALLABSENCE_5HTERM_AB143 ==.


gen OVERALLABSENCE_5HTERM_AB14 = OVERALLABSENCE_5HTERM_AB141 + OVERALLABSENCE_5HTERM_AB142 + OVERALLABSENCE_5HTERM_AB143 

summ OVERALLABSENCE_5HTERM_AB14, detail

gen absence_rate_14_5ht =  OVERALLABSENCE_5HTERM_AB14 / SESSIONSPOSSIBLE_5HTERM_AB14 *100
summ absence_rate_14_5ht, detail

gen absence_bin_14_5ht =.
replace absence_bin_14_5ht =1 if absence_rate_14_5ht >= 10 & absence_rate_14_5ht !=.
replace absence_bin_14_5ht =0 if absence_rate_14_5ht < 10
tab absence_bin_14_5ht, m

label variable absence_bin_14_5ht "binary absence 2014 10% 5HT"





gen absence14_flag =1

tab NCYEARACTUAL_AB141, m
tab NCYEARACTUAL_AB142, m
tab NCYEARACTUAL_AB143, m


codebook NCYEARACTUAL_AB141

*is the academic year the same for the duplicate entries for the same MCSID? 
count if NCYEARACTUAL_AB141 != NCYEARACTUAL_AB142 & NCYEARACTUAL_AB142 !="" & NCYEARACTUAL_AB141 !="" 
count if NCYEARACTUAL_AB141 != NCYEARACTUAL_AB143 & NCYEARACTUAL_AB143 !="" & NCYEARACTUAL_AB141 !="" /
count if NCYEARACTUAL_AB142 != NCYEARACTUAL_AB143 & NCYEARACTUAL_AB142 !="" & NCYEARACTUAL_AB143 !="" 

list CMID MCSID1 if NCYEARACTUAL_AB141 != NCYEARACTUAL_AB142 & NCYEARACTUAL_AB142 !="" & NCYEARACTUAL_AB141 !=""

count if NCYEARACTUAL_AB141 =="" &  NCYEARACTUAL_AB142 !="" 
count if NCYEARACTUAL_AB141 =="" &  NCYEARACTUAL_AB143 !="" 
count if NCYEARACTUAL_AB142 =="" &  NCYEARACTUAL_AB143 !="" 

encode NCYEARACTUAL_AB141, gen (NCYEARACTUAL_AB141_num)
encode NCYEARACTUAL_AB142, gen (NCYEARACTUAL_AB142_num)
encode NCYEARACTUAL_AB143, gen (NCYEARACTUAL_AB143_num)


codebook NCYEARACTUAL_AB141_num
tab NCYEARACTUAL_AB141
tab NCYEARACTUAL_AB141_num, m
tab NCYEARACTUAL_AB142_num, m
tab NCYEARACTUAL_AB143_num, m

*1 = year 7
*2 = year 8 
*3 = year 9


gen NCYEARACTUAL_AB14 =.
replace NCYEARACTUAL_AB14 = NCYEARACTUAL_AB141_num
replace NCYEARACTUAL_AB14 = NCYEARACTUAL_AB142_num if NCYEARACTUAL_AB14 ==.
replace NCYEARACTUAL_AB14 = NCYEARACTUAL_AB143_num if NCYEARACTUAL_AB14 ==.

label variable NCYEARACTUAL_AB14 "which academic year yp was in in 2014"

label define ncyear14 1 "7" 2 "8" 3 "9" 
label values NCYEARACTUAL_AB14 ncyear14

tab  NCYEARACTUAL_AB14, m 

sort NCYEARACTUAL_AB14
	  

 

keep CMID absence_rate_14_5ht absence_bin_14_5ht absence14_flag NCYEARACTUAL_AB14 unauthabsence_rate_14_5ht   authabsence_rate_14_5ht one_school

replace one_school =0 if one_school ==.

misstable summarize 

save "Working\all_waves_data_files\npd_2014_w.dta", replace



