*NPD 2014/15

cd 

use"mcs_cm_npd_absence_2015_restricted.dta", clear

*ID variables 
misstable summarize MCSID
tab CNUM, m 

*generating person specific ID 
egen CMID = concat (MCSID CNUM)  if CNUM >0

sort CMID
codebook CMID if CMID ! =""
count if CMID != ""
count if CMID == "" 

*duplicate IDs
duplicates list CMID
duplicates report CMID


duplicates tag CMID, generate(dup)


tab dup, m
sort dup CMID

gen one_school =.
replace one_school =1 if dup ==0
tab one_school, m

summ SESSIONSPOSSIBLE_5HTERM_AB15




*dfe guidance says schools should be open for at least 378 sessions per year

summ SESSIONSPOSSIBLE_6HTERM_AB15


*adding together duplicate rows 
*convert long to wide so each row is one individual with a unique CMID 
*also need to decide whether to use 5 or 6 half terms 
bysort CMID: gen cmid_dup = _n
reshape wide  MCSID CNUM MAINRECORD_AB15 URN_ANON_15 LEA_ANON_15 ONROLL_1_AB15 ONROLL_2_AB15 ONROLL_3_AB15 ACADEMICYEAR_AB15 GENDER_AB15 PHASE_AB15 YSSA_AB15 ENROLSTATUS_AB15 NCYEARACTUAL_AB15 SESSIONSPOSSIBLE_AUT_AB15 AUTHABSENCE_AUT_AB15 AUTHABSENCEFLAG_AUT_AB15 UNAUTHABSENCE_AUT_AB15 UNAUTHABSENCEFLAG_AUT_AB15 OVERALLABSENCE_AUT_AB15 SESSIONSPOSSIBLE_SPR_AB15 AUTHABSENCE_SPR_AB15 AUTHABSENCEFLAG_SPR_AB15 UNAUTHABSENCE_SPR_AB15 UNAUTHABSENCEFLAG_SPR_AB15 OVERALLABSENCE_SPR_AB15 SESSIONSPOSSIBLE_SUM_AB15 AUTHABSENCE_SUM_AB15 AUTHABSENCEFLAG_SUM_AB15 UNAUTHABSENCE_SUM_AB15 UNAUTHABSENCEFLAG_SUM_AB15 OVERALLABSENCE_SUM_AB15 SESSIONSPOSSIBLE_SUM6TH_AB15 AUTHABSENCE_SUM6TH_AB15 AUTHABSENCEFLAG_SUM6TH_AB15 UNAUTHABSENCE_SUM6TH_AB15 UNAUTHABSENCEFLAG_SUM6TH_AB15 OVERALLABSENCE_SUM6TH_AB15 SESSIONSPOSSIBLE_ANN_AB15 AUTHABSENCE_ANN_AB15 AUTHABSENCEFLAG_ANN_AB15 UNAUTHABSENCE_ANN_AB15 UNAUTHABSENCEFLAG_ANN_AB15 OVERALLABSENCE_ANN_AB15 SESSIONSPOSSIBLE_5HTERM_AB15 AUTHABSENCE_5HTERM_AB15 UNAUTHABSENCE_5HTERM_AB15 OVERALLABSENCE_5HTERM_AB15 SESSIONSPOSSIBLE_6HTERM_AB15 AUTHABSENCE_6HTERM_AB15 UNAUTHABSENCE_6HTERM_AB15 OVERALLABSENCE_6HTERM_AB15 , i (CMID) j (cmid_dup)

duplicates report CMID 

* 5 HALF TERMS

*sessions possible
replace SESSIONSPOSSIBLE_5HTERM_AB151 = 0 if SESSIONSPOSSIBLE_5HTERM_AB151 ==.
replace SESSIONSPOSSIBLE_5HTERM_AB152 = 0 if SESSIONSPOSSIBLE_5HTERM_AB152 ==.
replace SESSIONSPOSSIBLE_5HTERM_AB153 = 0 if SESSIONSPOSSIBLE_5HTERM_AB153 ==.
replace SESSIONSPOSSIBLE_5HTERM_AB154 = 0 if SESSIONSPOSSIBLE_5HTERM_AB154 ==.


gen SESSIONSPOSSIBLE_5HTERM_AB15 = SESSIONSPOSSIBLE_5HTERM_AB151 + SESSIONSPOSSIBLE_5HTERM_AB152 + SESSIONSPOSSIBLE_5HTERM_AB153 + SESSIONSPOSSIBLE_5HTERM_AB154 

summ SESSIONSPOSSIBLE_5HTERM_AB15, detail





*overall absence 
replace OVERALLABSENCE_5HTERM_AB151  = 0 if OVERALLABSENCE_5HTERM_AB151 ==.
replace OVERALLABSENCE_5HTERM_AB152  = 0 if OVERALLABSENCE_5HTERM_AB152 ==.
replace OVERALLABSENCE_5HTERM_AB153  = 0 if OVERALLABSENCE_5HTERM_AB153 ==.
replace OVERALLABSENCE_5HTERM_AB154  = 0 if OVERALLABSENCE_5HTERM_AB154 ==.


gen OVERALLABSENCE_5HTERM_AB15 = OVERALLABSENCE_5HTERM_AB151 + OVERALLABSENCE_5HTERM_AB152 + OVERALLABSENCE_5HTERM_AB153 + OVERALLABSENCE_5HTERM_AB154 

summ OVERALLABSENCE_5HTERM_AB15, detail

gen absence_rate_15_5ht =  OVERALLABSENCE_5HTERM_AB15 / SESSIONSPOSSIBLE_5HTERM_AB15 *100
summ absence_rate_15_5ht, detail

gen absence_bin_15_5ht =.
replace absence_bin_15_5ht =1 if absence_rate_15_5ht >= 10 & absence_rate_15_5ht !=.
replace absence_bin_15_5ht =0 if absence_rate_15_5ht < 10
tab absence_bin_15_5ht, m

label variable absence_bin_15_5ht "binary absence 2015 10% 5HT"




gen absence15_flag =1

tab NCYEARACTUAL_AB151, m
tab NCYEARACTUAL_AB152, m
tab NCYEARACTUAL_AB153, m
tab NCYEARACTUAL_AB154, m

codebook NCYEARACTUAL_AB151

*is the academic year the same for the duplicate entries for the same MCSID? 
count if NCYEARACTUAL_AB151 != NCYEARACTUAL_AB152 & NCYEARACTUAL_AB152 !="" & NCYEARACTUAL_AB151 !="" 
count if NCYEARACTUAL_AB151 != NCYEARACTUAL_AB153 & NCYEARACTUAL_AB153 !="" & NCYEARACTUAL_AB151 !="" 
count if NCYEARACTUAL_AB152 != NCYEARACTUAL_AB153 & NCYEARACTUAL_AB152 !="" & NCYEARACTUAL_AB153 !="" 

list CMID MCSID1 if NCYEARACTUAL_AB151 != NCYEARACTUAL_AB152 & NCYEARACTUAL_AB152 !="" & NCYEARACTUAL_AB151 !=""

count if NCYEARACTUAL_AB151 =="" &  NCYEARACTUAL_AB152 !="" 
count if NCYEARACTUAL_AB151 =="" &  NCYEARACTUAL_AB153 !="" 
count if NCYEARACTUAL_AB152 =="" &  NCYEARACTUAL_AB153 !="" 

encode NCYEARACTUAL_AB151, gen (NCYEARACTUAL_AB151_num)
encode NCYEARACTUAL_AB152, gen (NCYEARACTUAL_AB152_num)
encode NCYEARACTUAL_AB153, gen (NCYEARACTUAL_AB153_num)
encode NCYEARACTUAL_AB154, gen (NCYEARACTUAL_AB154_num)


codebook NCYEARACTUAL_AB151_num
tab NCYEARACTUAL_AB151
tab NCYEARACTUAL_AB151_num, m
tab NCYEARACTUAL_AB152_num, m
tab NCYEARACTUAL_AB153_num, m

*1 = year 10
*2 = year 8 
*3 = year 9


gen NCYEARACTUAL_AB15 =.
replace NCYEARACTUAL_AB15 = NCYEARACTUAL_AB151_num
replace NCYEARACTUAL_AB15 = NCYEARACTUAL_AB152_num if NCYEARACTUAL_AB15 ==.
replace NCYEARACTUAL_AB15 = NCYEARACTUAL_AB153_num if NCYEARACTUAL_AB15 ==.
replace NCYEARACTUAL_AB15 = NCYEARACTUAL_AB154_num if NCYEARACTUAL_AB15 ==.

label variable NCYEARACTUAL_AB15 "which academic year yp was in in 2015"

label define ncyear15 1 "10" 2 "8" 3 "9" 
label values NCYEARACTUAL_AB15 ncyear15

tab  NCYEARACTUAL_AB15, m 

*almost everyone is in year 9 in 2014/15 academic year 

sort NCYEARACTUAL_AB15
	  

 

keep CMID absence_rate_15_5ht absence_bin_15_5ht absence15_flag NCYEARACTUAL_AB15 unauthabsence_rate_15_5ht   authabsence_rate_15_5ht one_school

replace one_school =0 if one_school ==.

misstable summarize 
save "Working\all_waves_data_files\npd_2015_w.dta", replace



